modLoader = "javafml"
loaderVersion = "[43,)"
license = "GNU LESSER GENERAL PUBLIC LICENSE Version 2.1"
[[mods]]
modId = "dawncraft"
version = "${file.jarVersion}"
displayName = "DawnCraft-Tweaks"
description = '''

'''
[[dependencies.dawncraft]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.dawncraft]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2)"
ordering = "NONE"
side = "BOTH"
[[dependencies.dawncraft]]
modId = "atlaslib"
mandatory = true
versionRange = "[1.1.6,)"
ordering = "NONE"
side = "BOTH"

[[mods]]
modId = "afptweaks"
version = "${file.jarVersion}"
displayName = "AFPTweaks ProxyLoader"
description = ''''''